# Generated by Django 4.0.6 on 2022-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentificacion', '0002_profile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media\x07vatares\\Acces.jpg', upload_to=''),
        ),
    ]
