# Generated by Django 4.0.6 on 2022-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('cantidad_consultas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=9000)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
